DROP VIEW TRAINING_UPDATE;
DROP VIEW SUMMARY;
DROP VIEW TOTAL_EXPENSES;
DROP VIEW EXPENSES_VIEW;
DROP VIEW UPCOMING_INSPECTIONS;
DROP VIEW SUPPLIER_REPORT;

DROP TABLE TRAINING;
DROP SEQUENCE TRAININGID;

DROP TABLE WORKERS;
DROP SEQUENCE WORKERID;

DROP TABLE INSPECTIONS;
DROP SEQUENCE INSPECTIONID;

DROP TABLE BUDGET;
DROP SEQUENCE BUDGETID;

DROP TABLE SAFETY_INCIDENTS;
DROP SEQUENCE INCIDENTID;

DROP TABLE PURCHASE_ORDERS;
DROP SEQUENCE ORDERSID;

DROP TABLE PERMITS;
DROP SEQUENCE PERMITID;

DROP TABLE MARKETING;
DROP SEQUENCE MARKETINGID;

DROP TABLE ARCHITECTURE;
DROP SEQUENCE ARCHITECTUREID;

DROP TABLE PROJECT_LOCATION_DATA;
DROP SEQUENCE LOCATIONID;

DROP TABLE EXPENSES;
DROP SEQUENCE EXPENSEID;

DROP TABLE CONSTRUCTION_PROJECTS;
DROP SEQUENCE PROJECTID;

DROP TABLE CONTRACTORS;
DROP SEQUENCE CONTRACTORID;

DROP TABLE MANAGERS;
DROP SEQUENCE MANAGERID;

DROP TABLE PROJECT_COSTS;

DROP SEQUENCE PROJECT_COST_SQ ;
DROP TABLE PROJECT_COSTS;
